image:
    registry.comtom.cn:2443/publicimage/docker:18.09.8-dind

stages:
    - windows
    - put_ftp
    - compile_centos7.9
    - docker_image
    - compile_arm64

variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_AUTH_CONFIG: '{"auths": {"registry.comtom.cn:2443": {"auth": "c3RhcmJjOjFxYXpAV1NY"}}}'

services:
    - docker:18.09.8-dind

compile_arm64:
    stage: compile_arm64
    only: 
        - develop
        - release
        - master
    image:
        registry.comtom.cn:2443/starbc-dev/star-compile-arm64:0.2
    before_script:
        - COMMIT=${CI_COMMIT_SHA:0:7}
        - VERSION=`cat version`
        - REPO=`if [[ ${CI_COMMIT_REF_NAME:0:6} = "master" ]]; then echo r; elif [[ ${CI_COMMIT_REF_NAME:0:7} = "release" ]]; then echo b; else echo a; fi`;
        - DATE=`echo $(date +%Y%m%d)`
        - DOCKERREPO=`if [[ ${CI_COMMIT_REF_NAME:0:6} = "master" ]]; then echo starbc-release; elif [[ ${CI_COMMIT_REF_NAME:0:7} = "release" ]]; then echo starbc-test; else echo starbc-dev; fi`;
        - DOCKERREPOEWBS=`if [[ ${CI_COMMIT_REF_NAME:0:6} = "master" ]]; then echo ct-ewbs-release; elif [[ ${CI_COMMIT_REF_NAME:0:7} = "release" ]]; then echo ct-ewbs-test; else echo ct-ewbs-dev; fi`;
        - ENABLE_DEBUG=`if [[ ${CI_COMMIT_REF_NAME:0:6} = "master" ]]; then echo false; elif [[ ${CI_COMMIT_REF_NAME:0:7} = "release" ]]; then echo false; else echo true; fi`;
    script:
        - rm -f star_pushersvr_*.tar.gz
        - wget http://git.comtom.cn:18000/3rdPartTool/curl/uploads/fd2dc697dd57459f02b6f94c02182a03/curl-7.78.0-arm64.tar.gz -P /opt
        - tar zxf /opt/curl-7.78.0-arm64.tar.gz -C /usr/local/
        - export CURL_ROOT=/usr/local/curl-7.78.0-arm64
        - wget http://git.comtom.cn:18000/3rdPartTool/ffmpeg/uploads/bbd476c5d6b2e3807b6733218d870e7c/ffmpeg-n4.4.1.tar.gz -P /opt
        - tar zxf /opt/ffmpeg-n4.4.1.tar.gz -C /usr/local
        - export FFMPEG_ROOT=/usr/local/ffmpeg-n4.4.1
        - wget http://git.comtom.cn:18000/3rdPartTool/lame/uploads/0029fc5a435ed3c9479cb51569ec7a36/lame-3.100-arm64.tar.gz -P /opt
        - tar zxf /opt/lame-3.100-arm64.tar.gz -C /usr/local/
        - export LAME_ROOT=/usr/local/lame-3.100-arm64
        - wget http://git.comtom.cn:18000/tbcloud-sdks/tbss_pusher/uploads/732a2aa6e3d94eb091ea78ff9c301f18/rtmp_pusher-aarch64-1.1.3.34a-dd60724-20230106.tar.gz -P /opt
        - tar zxf /opt/rtmp_pusher-aarch64-1.1.3.34a-dd60724-20230106.tar.gz -C /usr/local/
        - export RTMPPUSHER_ROOT=/usr/local/rtmp_pusher-aarch64-1.1.3.34a-dd60724-20230106
        - wget http://git.comtom.cn:18000/tbcloud-sdks/rtsppushersdk/uploads/c59eae5e299c3c686a0b37da6e40776f/rtsp_pusher-aarch64-1.0.1.2b-d370202-20230111.tar.gz -P /opt
        - tar zxf /opt/rtsp_pusher-aarch64-1.0.1.2b-d370202-20230111.tar.gz -C /usr/local/
        - export RTSPPUSHER_ROOT=/usr/local/rtsp_pusher-aarch64-1.0.1.2b-d370202-20230111
        - export TARGET=star_pushersvr_${VERSION}${REPO}-${COMMIT}-arm64-${DATE}
        - echo ${TARGET}
        - cd star_pushersvr
        - VERSION=${VERSION}${REPO}-${COMMIT}-arm64-${DATE} ENABLE_DEBUG=${ENABLE_DEBUG} make arm64
        - mkdir ${TARGET} 
        - mv build/star_pushersvr ${TARGET} 
        - cp install.sh star_pushersvr.service conf/*.json ${TARGET} 
        - cp -rf media ${TARGET} 
        - mkdir ${TARGET}/3rd
        - cp ${ACE_ROOT}/lib/libACE.so.6.5.0 ${TARGET}/3rd
        - cp ${THRIFT_ROOT}/lib/libthrift-0.14.1.so ${TARGET}/3rd
        - cp ${OPENSSL_ROOT}/lib/libssl.so.1.1 ${TARGET}/3rd
        - cp ${OPENSSL_ROOT}/lib/libcrypto.so.1.1 ${TARGET}/3rd
        - cp ${JSONCPP_ROOT}/lib/libjsoncpp.so* ${TARGET}/3rd
        - cp ${HIREDIS_ROOT}/lib/libhiredis.so.1.0.0 ${TARGET}/3rd
        - cp ${REDISPLUSPLUS_ROOT}/lib/libredis++.so.1 ${TARGET}/3rd
        - cp ${CURL_ROOT}/lib/libcurl.so* ${TARGET}/3rd
        - cp ${RTMPPUSHER_ROOT}/lib/libstreampusher.so ${TARGET}/3rd
        - cp ${RTSPPUSHER_ROOT}/lib/libRTSPPusher.so ${TARGET}/3rd
        - mkdir ${TARGET}/ffmpeg
        - cp ${FFMPEG_ROOT}/lib/libavutil.so.56 ${TARGET}/ffmpeg
        - cp ${FFMPEG_ROOT}/lib/libswresample.so.3 ${TARGET}/ffmpeg
        - cp ${FFMPEG_ROOT}/lib/libavformat.so.58 ${TARGET}/ffmpeg
        - cp ${FFMPEG_ROOT}/lib/libavcodec.so.58 ${TARGET}/ffmpeg
        - cp ${FFMPEG_ROOT}/lib/libavfilter.so.7 ${TARGET}/ffmpeg
        - cp ${FFMPEG_ROOT}/lib/libswscale.so.5 ${TARGET}/ffmpeg
        - tar -czvf ${TARGET}.tar.gz ${TARGET}
        - mv ${TARGET}.tar.gz ..
    artifacts:
        expire_in: 1 week
        when: on_success
        paths:
            - star_pushersvr_*.tar.gz

compile_centos7.9:
    stage: compile_centos7.9
    only: 
        - develop
        - release
        - master
    image:
        registry.comtom.cn:2443/starbc-dev/star-compile-centos7.9:0.2
    before_script:
        - COMMIT=${CI_COMMIT_SHA:0:7}
        - VERSION=`cat version`
        - REPO=`if [[ ${CI_COMMIT_REF_NAME:0:6} = "master" ]]; then echo r; elif [[ ${CI_COMMIT_REF_NAME:0:7} = "release" ]]; then echo b; else echo a; fi`;
        - DATE=`echo $(date +%Y%m%d)`
        - DOCKERREPO=`if [[ ${CI_COMMIT_REF_NAME:0:6} = "master" ]]; then echo starbc-release; elif [[ ${CI_COMMIT_REF_NAME:0:7} = "release" ]]; then echo starbc-test; else echo starbc-dev; fi`;
        - DOCKERREPOEWBS=`if [[ ${CI_COMMIT_REF_NAME:0:6} = "master" ]]; then echo ct-ewbs-release; elif [[ ${CI_COMMIT_REF_NAME:0:7} = "release" ]]; then echo ct-ewbs-test; else echo ct-ewbs-dev; fi`;
        - ENABLE_DEBUG=`if [[ ${CI_COMMIT_REF_NAME:0:6} = "master" ]]; then echo false; elif [[ ${CI_COMMIT_REF_NAME:0:7} = "release" ]]; then echo false; else echo true; fi`;
    script:
        - rm -f star_pushersvr_*.tar.gz
        - wget http://git.comtom.cn:18000/3rdPartTool/curl/uploads/a87f61b0a3e7b868af4906b014720ad6/curl-7.78.0-centos7.9.tar.gz -P /opt
        - tar zxf /opt/curl-7.78.0-centos7.9.tar.gz -C /usr/local/
        - export CURL_ROOT=/usr/local/curl-7.78.0-centos7.9
        - wget http://git.comtom.cn:18000/3rdPartTool/ffmpeg/uploads/ed94e6d83a3dbcd63afe0c1042ccdc20/ffmpeg-n4.4.1-with-mp3lame-openssl.tar.gz -P /opt
        - tar zxf /opt/ffmpeg-n4.4.1-with-mp3lame-openssl.tar.gz -C /usr/local/
        - export FFMPEG_ROOT=/usr/local/ffmpeg-n4.4.1-with-mp3lame-openssl
        - wget http://git.comtom.cn:18000/3rdPartTool/lame/uploads/424c3ef4b98e0903c42b7eb06bf507b7/lame-3.100-centos7.9.tar.gz -P /opt
        - tar zxf /opt/lame-3.100-centos7.9.tar.gz -C /usr/local/
        - export LAME_ROOT=/usr/local/lame-3.100-centos7.9
        - wget http://git.comtom.cn:18000/tbcloud-sdks/tbss_pusher/uploads/63d5608ab6109f76a983f7bdd76d004e/rtmp_pusher-amd64-1.1.3.34a-dd60724-20230106.tar.gz -P /opt
        - tar zxf /opt/rtmp_pusher-amd64-1.1.3.34a-dd60724-20230106.tar.gz -C /usr/local/
        - export RTMPPUSHER_ROOT=/usr/local/rtmp_pusher-amd64-1.1.3.34a-dd60724-20230106
        - wget http://git.comtom.cn:18000/tbcloud-sdks/rtsppushersdk/uploads/ee478ff72b8e7fd50ac0b5fea4d6a14a/rtsp_pusher-amd64-1.0.1.2b-d370202-20230111.tar.gz -P /opt
        - tar zxf /opt/rtsp_pusher-amd64-1.0.1.2b-d370202-20230111.tar.gz -C /usr/local/
        - export RTSPPUSHER_ROOT=/usr/local/rtsp_pusher-amd64-1.0.1.2b-d370202-20230111
        - export TARGET=star_pushersvr_${VERSION}${REPO}-${COMMIT}-centos7.9-${DATE}
        - echo ${TARGET}
        - cd star_pushersvr
        - source scl_source enable devtoolset-7 && VERSION=${VERSION}${REPO}-${COMMIT}-centos7.9-${DATE} ENABLE_DEBUG=${ENABLE_DEBUG} make centos
        - mkdir ${TARGET} 
        - mv build/star_pushersvr ${TARGET} 
        - cp install.sh star_pushersvr.service conf/*.json ${TARGET} 
        - cp -rf media ${TARGET} 
        - mkdir ${TARGET}/3rd
        - cp ${ACE_ROOT}/lib/libACE.so.6.5.0 ${TARGET}/3rd
        - cp ${OPENSSL_ROOT}/lib/libssl.so.1.1 ${TARGET}/3rd
        - cp ${OPENSSL_ROOT}/lib/libcrypto.so.1.1 ${TARGET}/3rd
        - cp ${CURL_ROOT}/lib/libcurl.so.4 ${TARGET}/3rd
        - cp ${RTMPPUSHER_ROOT}/lib/libstreampusher.so ${TARGET}/3rd
        - cp ${RTSPPUSHER_ROOT}/lib/libRTSPPusher.so ${TARGET}/3rd
        - mkdir ${TARGET}/ffmpeg
        - cp ${FFMPEG_ROOT}/lib/libavutil.so.56 ${TARGET}/ffmpeg
        - cp ${FFMPEG_ROOT}/lib/libswresample.so.3 ${TARGET}/ffmpeg
        - cp ${FFMPEG_ROOT}/lib/libavformat.so.58 ${TARGET}/ffmpeg
        - cp ${FFMPEG_ROOT}/lib/libavcodec.so.58 ${TARGET}/ffmpeg
        - cp ${FFMPEG_ROOT}/lib/libavfilter.so.7 ${TARGET}/ffmpeg
        - cp ${FFMPEG_ROOT}/lib/libswscale.so.5 ${TARGET}/ffmpeg
        - cp ${LAME_ROOT}/lib/libmp3lame.so.0 ${TARGET}/ffmpeg
        - tar -czvf ${TARGET}.tar.gz ${TARGET}
        - mv ${TARGET}.tar.gz ..
    artifacts:
        expire_in: 1 week
        when: on_success
        paths:
            - star_pushersvr_*.tar.gz

docker_image:
    stage: docker_image
    only: 
        - develop
        - release
        - master
    before_script:
        - COMMIT=${CI_COMMIT_SHA:0:7}
        - VERSION=`cat version`
        - REPO=`if [[ ${CI_COMMIT_REF_NAME:0:6} = "master" ]]; then echo r; elif [[ ${CI_COMMIT_REF_NAME:0:7} = "release" ]]; then echo b; else echo a; fi`;
        - DATE=`echo $(date +%Y%m%d)`
        - DOCKERREPO=`if [[ ${CI_COMMIT_REF_NAME:0:6} = "master" ]]; then echo starbc-release; elif [[ ${CI_COMMIT_REF_NAME:0:7} = "release" ]]; then echo starbc-test; else echo starbc-dev; fi`;
        - DOCKERREPOEWBS=`if [[ ${CI_COMMIT_REF_NAME:0:6} = "master" ]]; then echo ct-ewbs-release; elif [[ ${CI_COMMIT_REF_NAME:0:7} = "release" ]]; then echo ct-ewbs-test; else echo ct-ewbs-dev; fi`;
    script:
        - echo "$REGISTRY_PASSWD" | docker login registry.comtom.cn:2443 --username $REGISTRY_USER --password-stdin
        - export IMAGETAG=${VERSION}${REPO}.${COMMIT}
        - tar -xzvf star_pushersvr_${VERSION}${REPO}-${COMMIT}-centos7.9-${DATE}.tar.gz
        - cp -rf star_pushersvr_${VERSION}${REPO}-${COMMIT}-centos7.9-${DATE}/* docker
        - cd docker
        - docker build -t registry.comtom.cn:2443/${DOCKERREPO}/star_pushersvr:${IMAGETAG} .
        - docker tag registry.comtom.cn:2443/${DOCKERREPO}/star_pushersvr:${IMAGETAG} registry.comtom.cn:2443/${DOCKERREPO}/star_pushersvr:latest
        - docker tag registry.comtom.cn:2443/${DOCKERREPO}/star_pushersvr:${IMAGETAG} registry.comtom.cn:2443/${DOCKERREPOEWBS}/star_pushersvr:${IMAGETAG}
        - docker tag registry.comtom.cn:2443/${DOCKERREPO}/star_pushersvr:${IMAGETAG} registry.comtom.cn:2443/${DOCKERREPOEWBS}/star_pushersvr:latest
        - docker push registry.comtom.cn:2443/${DOCKERREPO}/star_pushersvr:${IMAGETAG}
        - docker push registry.comtom.cn:2443/${DOCKERREPO}/star_pushersvr:latest
        - docker push registry.comtom.cn:2443/${DOCKERREPOEWBS}/star_pushersvr:${IMAGETAG}
        - docker push registry.comtom.cn:2443/${DOCKERREPOEWBS}/star_pushersvr:latest
        - docker rmi registry.comtom.cn:2443/${DOCKERREPO}/star_pushersvr:${IMAGETAG}
        - docker rmi registry.comtom.cn:2443/${DOCKERREPO}/star_pushersvr:latest
        - docker rmi registry.comtom.cn:2443/${DOCKERREPOEWBS}/star_pushersvr:${IMAGETAG}
        - docker rmi registry.comtom.cn:2443/${DOCKERREPOEWBS}/star_pushersvr:latest

windows:
    stage: windows
    only: 
        - develop_bosch
        - release_bosch
        - master_bosch
    tags:
        - vs2017
    script:
        - $COMMIT = $CI_COMMIT_SHA.substring(0, 7)
        - $VERSION = cat version
        - $DATE = Get-Date -Format 'yyyyMMdd'
        - $REPO = if ($CI_COMMIT_REF_NAME.length -gt 5 -and $CI_COMMIT_REF_NAME.substring(0, 6) -eq "master") {echo r} elseif ($CI_COMMIT_REF_NAME.length -gt 6 -and $CI_COMMIT_REF_NAME.substring(0, 7) -eq "release") {echo b} else {echo a}
        - $TARGET = echo star_pushersvr_$VERSION$REPO-$COMMIT-windows-$DATE

        - devenv.com star_pushersvr.sln /Build "Release|x64"

        - mkdir ${TARGET}\bin,${TARGET}\log,${TARGET}\data,${TARGET}\conf
        - copy x64\Release\star_pushersvr.exe ${TARGET}\bin -force
        - copy $Env:ACE_ROOT\lib64\ACE.dll ${TARGET}\bin -force
        - copy $Env:FFMPEG_ROOT\bin\*.dll ${TARGET}\bin -force
        - copy $Env:CURL_ROOT\lib64\libcurl.dll ${TARGET}\bin -force
        - copy $Env:RTMPPUSHER_ROOT\lib64\librtmp.dll ${TARGET}\bin -force
        - copy $Env:RTMPPUSHER_ROOT\lib64\rtmppusher.dll ${TARGET}\bin -force
        - copy windows_install\* ${TARGET} -force -Recurse
        - copy star_pushersvr\media\* ${TARGET}\data -force

    artifacts:
        expire_in: 1 week
        when: on_success
        paths:
            - star_pushersvr_*windows*

put_ftp_bosch:
    stage: put_ftp
    only: 
        - develop_bosch
        - release_bosch
        - master_bosch
    image:
        registry.comtom.cn:2443/publicimage/lftp:latest
    tags:
        - dind
    script:
        - echo '开始上传到ftp'
        - pwd
        - ls
        - tar -zcvf star_pushersvr.tar.gz star_pushersvr_*windows*
        - lftp $FTP_SERVER_HOST -u bosch,123456 -e "put star_pushersvr.tar.gz" 